### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by tagener-noisu** [Sayales/LocalPicDump#1]
Спасибо, что выполнил реквест. Буду рад если напишешь как все это запустить.

**Comment by Sayales** [comment]
Написал в readme. Grails вроде как не позволяет получать данные для коннекта к базе с формы, поэтому вот так вот криво. Можно в LocalPicDump/grails-app/conf/DataSource.groovy прописать свои настройки для коннекта, и самостоятельно собрать war файл, для этого нужен grails v2.5.5.
